name: Docker Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest-crypto # specify runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      #- name: Set up Docker Buildx
      #  uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t my-docker-image-from-ci-cd-3 .