name: Docker Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest-crypto # specify runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker prerequisites
        run: |
          # Install iptables and other required dependencies
          sudo dnf install -y iptables iptables-nft iptables-legacy
          sudo dnf install -y device-mapper-persistent-data lvm2

      - name: Set up Docker
        uses: docker/setup-docker-action@v4

      - name: Build Docker image
        run: |
          docker build -t my-docker-image-from-ci-cd-3 .